# Generated by Django 6.0 on 2025-12-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sutakibi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciHedefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_kilo', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hedef_kilo', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hedef_turu', models.CharField(choices=[('VER', 'Kilo Vermek'), ('AL', 'Kilo Almak'), ('KORU', 'Kiloyu Korumak')], default='VER', max_length=10)),
                ('boy', models.IntegerField(help_text='cm cinsinden')),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='kilokaydi',
            name='olusturulma_tarihi',
        ),
        migrations.RemoveField(
            model_name='kilokaydi',
            name='user',
        ),
        migrations.AlterField(
            model_name='sutakibi',
            name='tarih',
            field=models.DateField(),
        ),
    ]
