# Generated by Django 6.0 on 2025-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kullanicihedefi_remove_kilokaydi_olusturulma_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilokaydi',
            name='notlar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
